#-------------------------------------------------------------------------------------------------------
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------

name: KeyboarInputDetector

configFiles:
  Debug: Library/project.xcconfig
  Release: Library/project.xcconfig

targets:
#-------------------------------------------------------------------------------------------------------
# iOS framework for iOS example & unity asset for ios deveice
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
  KeyboarInputDetector:
    type: framework
    platform: iOS
    deploymentTarget: 12.0

    configFiles:
      Debug: Library/Platforms/iOS/iOS.xcconfig
      Release: Library/Platforms/iOS/iOS.xcconfig

    settings:
      INFOPLIST_FILE: Library/Platforms/iOS/info.plist
      SUPPORTS_MACCATALYST: NO
      SUPPORTED_PLATFORMS: iphoneos
      PRODUCT_BUNDLE_IDENTIFIER: factory.fuziki.framework.ios

    sources:
      - path: Library/Sources
        name: Sources
        group: Library
        createIntermediateGroups: true

      - path: Library/Platforms/iOS
        name: iOS
        group: Library/Platforms
        createIntermediateGroups: true

      - path: Library/Sources/NativePlugin.h
        buildPhase: headers
        headerVisibility: public

    postBuildScripts:
      - path: Library/Scripts/CopyFramework.sh
        name: CopyFramework

#-------------------------------------------------------------------------------------------------------
# macOS framework for macOS example
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
  KeyboarInputDetector_macOS:
    type: framework
    platform: macOS
    deploymentTarget: 10.14

    configFiles:
      Debug: Library/Platforms/macOS/Framework/macOS.xcconfig
      Release: Library/Platforms/macOS/Framework/macOS.xcconfig

    settings:
      INFOPLIST_FILE: Library/Platforms/macOS/Framework/info.plist

    sources:
      - path: Library/Sources
        name: Sources
        group: Library
        createIntermediateGroups: true

      - path: Library/Platforms/macOS/Framework
        name: Framework
        group: Library/Platforms/macOS
        createIntermediateGroups: true

      - path: Library/Sources/NativePlugin.h
        buildPhase: headers
        headerVisibility: public

#-------------------------------------------------------------------------------------------------------
# bundle for unity macOS editor
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
  KeyboarInputDetector_bundle:
    type: bundle
    platform: macOS
    deploymentTarget: 10.14

    configFiles:
      Debug: Library/Platforms/macOS/Bundle/macOS.xcconfig
      Release: Library/Platforms/macOS/Bundle/macOS.xcconfig

    settings:
      PRODUCT_NAME: $(OUTPUT_UNIQUE_NAME)
      INFOPLIST_FILE: Library/Platforms/macOS/Bundle/info.plist

    sources:
      - path: Library/Sources
        name: Sources
        group: Library
        createIntermediateGroups: true

      - path: Library/Platforms/macOS/Bundle
        name: Bundle
        group: Library/Platforms/macOS
        createIntermediateGroups: true
        excludes:
          - "*.cs"
          - "cs_maker/**"
          - "rs/**"

      - path: Library/Sources/NativePlugin.h
        buildPhase: headers
        headerVisibility: public

    postBuildScripts:
      - path: Library/Scripts/CopyBundle.sh
        name: CopyBundle

#-------------------------------------------------------------------------------------------------------
# example iOS
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
  Example_iOS:
    type: application
    platform: iOS
    deploymentTarget: 13.0

    settings:
      INFOPLIST_FILE: Example/iOS/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: factory.fuziki.example
      SWIFT_OBJC_BRIDGING_HEADER: ${PROJECT_DIR}/Example/iOS/Example_iOS-Bridging-Header.h
      GCC_PREPROCESSOR_DEFINITIONS: $(inherited) FRAMEWORK_HEADER=<KeyboarInputDetector/NativePlugin.h>

    sources:
      - path: Example/iOS
        name: iOS
        group: Example
        createIntermediateGroups: true

    dependencies:
      - target: KeyboarInputDetector

#-------------------------------------------------------------------------------------------------------
# example macOS
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
  Example_macOS:
    type: application
    platform: macOS
    deploymentTarget: 10.14

    settings:
      INFOPLIST_FILE: Example/macOS/info.plist
      CODE_SIGN_IDENTITY: "-"
      SWIFT_OBJC_BRIDGING_HEADER: ${PROJECT_DIR}/Example/macOS/Example_macOS-Bridging-Header.h
      GCC_PREPROCESSOR_DEFINITIONS: $(inherited) FRAMEWORK_HEADER=<KeyboarInputDetector_macOS/NativePlugin.h>

    sources:
      - path: Example/macOS
        name: macOS
        group: Example
        createIntermediateGroups: true

    dependencies:
      - target: KeyboarInputDetector_macOS

#-------------------------------------------------------------------------------------------------------
# scheme setteing
# Don't edit this file!!
#-------------------------------------------------------------------------------------------------------
schemes:
  KeyboarInputDetector_bundle:
    build:
      targets:
        KeyboarInputDetector_bundle: macOS
      preActions:
        - script: sh ${PROJECT_DIR}/Library/Scripts/PreAction.sh
          settingsTarget: KeyboarInputDetector_bundle
